### ISSUE TITLE
Wrong reference of Lab5 Ex 5 in `lab6/el5373-lab6-611.md`?

### ISSUE THREAD

**Issue by ly4096x** [ffund/tcp-ip-essentials#1]
In `lab6/el5373-lab6-611.md` there is:

__Lab report__: Did you observe any IP fragmentation? If IP fragmentation did not occur this time, how do you explain this compared to what you observed in Exercise 5 of Chapter 5?

However Lab 5 has no Ex 5.

**Comment by ffund** [comment]
Thank you for the correction, I updated the reference!
